version: "3.8"
services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: /code/src/server-entrypoint.sh
    expose:
      - 8000
    env_file:
      ./src/.env 
    ports:
      - 9000:8000
      - 8000:8000
    tty: true
    volumes:
      - ./src/db:/code/src/db
  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /code/src/worker-entrypoint.sh
    env_file:
      ./src/.env 
    depends_on:
      - django
      - redis
    volumes:
      - ./src/db:/code/src/db
  celery_beat:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      ./src/.env
    command: celery -A sendings beat -l debug
    working_dir: /code/src/
    depends_on:
      - worker
      - redis
    volumes:
      - ./src:/code/src
  redis:
    restart: unless-stopped
    image: redis:6.2.12
    env_file:
      ./src/.env 
    expose: 
      - 6379